language: "python"
dist: xenial
sudo: true
python:
  - "3.6"
# Command to install dependencies
install:
  - sudo apt update -qq
  - sudo apt install -qq libopenmpi-dev swig make
  - pip install --quiet -r travis-requirements.txt
# Command to run tests
script:
  - make test
